### ISSUE TITLE
Option for Postgres Driver

### ISSUE THREAD

**Issue by salaback** [laravel-fans/laravel-docker#37]
I have been having an issue switching out the mysql drivers for postgres in this. It would seem that support for Postgres would be equally high for production situations.  Maybe could be even added as configuration option when publishing so that the image doesn't get overloaded with multiple db drivers.

**Comment by sinkcup** [comment]
thanks for your feedback.
are you using docker hub `laravelfans/laravel` in production?
it's not a good idea.
I suggest to use composer `laravel-fans/docker` in production, it will publish `Dockerfile` to your laravel project, and you could modify it for your db driver.
docs: https://github.com/laravel-fans/laravel-docker/blob/main/README.md
