### ISSUE TITLE
Error on Macos

### ISSUE THREAD

**Issue by echo-LuGuang** [laravel-fans/laravel-docker#56]
error:
<img width="1512" alt="image" src="https://github.com/laravel-fans/laravel-docker/assets/50095011/eb8c97a8-09c2-4175-b7e2-590524dd287f">

<br />

php version:
<img width="574" alt="image" src="https://github.com/laravel-fans/laravel-docker/assets/50095011/86eed83a-003c-4f4d-8af4-f690175ae788">

感觉是File::copyDirectory的options参数的问题，也许macos上不支持。 我去掉参数正常。

**Comment by sinkcup** [comment]
我在 macOS 14.0 + PHP 8.1.23 环境中运行成功，也许是不支持 PHP 8.2？我再试试

<img width="897" alt="image" src="https://github.com/laravel-fans/laravel-docker/assets/4971414/1bf19268-569c-4a24-8ecd-c8709597d729">

**Comment by sinkcup** [comment]
PHP 8.3 也报错……

没想起来当初为什么加这个参数，网上也没查到这个参数的意义，去掉也能正常使用，于是决定去掉。
